### ISSUE TITLE
When using range option, changes to ng-model outside the slider do not function

### ISSUE THREAD

**Issue by xiphiaz** [seiyria/angular-bootstrap-slider#47]
When I use a simple slider I can externally (another input or in controller) change the `ng-model` value of the slider, and the slider slides accordingly. This does not work for a range slider.

See example:

```html
Range Slider (binds only one way)
<slider
    ng-model="exampleModel"
    value="exampleModel"
    min="0"
    step="1"
    max="10"
    range="true"
></slider>

Min:
<input
    type="number"
    min="0"
    max="10"
    step="1"
    ng-model="exampleModel[0]"
/>
Max:
<input
    type="number"
    min="0"
    max="10"
    step="1"
    ng-model="exampleModel[1]"
/>

Min Slider(works)
<slider
    ng-model="exampleModel[0]"
    value="exampleModel[0]"
    min="0"
    step="1"
    max="10"
></slider>
```

There should be two way binding on the model.

**Comment by bitfidget** [comment]
I've just found this also - there is no two-way data binding on the model: the slider can update the model, but it seems the model cannot update the slider (it does, but only on initial render).

**Comment by seiyria** [comment]
This should work now, as per a recent update.

**Comment by xiphiaz** [comment]
Is it fixed? I checked by forking the plunkr from the last PR with my test code and it seems like there is still an issue. See http://plnkr.co/edit/5rfELcz2KmZZseQ4A1QC?p=preview

**Comment by seiyria** [comment]
Hm, seems you're right, my bad.

**Comment by andreaslarssen** [comment]
+1

**Comment by xiphiaz** [comment]
@seiyria I just re-checked my old plunkr and it looks like it has been fixed, can you confirm?

**Comment by seiyria** [comment]
Yep, looks like it works now.
